#!/usr/bin/env node
/**
 * AI-powered PR review script.
 * Usage: node scripts/review-pr.js <PR_NUMBER>
 *
 * 1. Fetches PR diff via `gh pr diff`
 * 2. Sends diff to Together AI (via llm.js) with a code review prompt
 * 3. Posts the review as a GitHub PR comment via `gh pr comment`
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });

const { execSync } = require('child_process');
const { callLLM } = require('../server/services/llm');

const REVIEW_PROMPT = `You are a senior software engineer performing a thorough code review.
Analyze the following git diff and provide a structured review covering:

1. **Logic Bugs / Edge Cases** — incorrect logic, off-by-one errors, unhandled nulls, race conditions
2. **Security Issues** — SQL injection, unvalidated input, auth gaps, secrets exposure, XSS
3. **Performance Concerns** — N+1 queries, missing indexes, unnecessary allocations, blocking operations
4. **Code Style / Consistency** — naming, formatting, patterns inconsistent with the codebase
5. **Missing Tests** — untested code paths, edge cases that need coverage
6. **Suggestions** — improvements, simplifications, better abstractions

Be specific. Reference file names and line numbers from the diff. If something looks good, say so briefly.
Keep the review concise and actionable. Use markdown formatting.`;

async function main() {
  const prNumber = process.argv[2];
  if (!prNumber || isNaN(prNumber)) {
    console.error('Usage: node scripts/review-pr.js <PR_NUMBER>');
    process.exit(1);
  }

  console.log(`Fetching diff for PR #${prNumber}...`);
  let diff;
  try {
    diff = execSync(`gh pr diff ${prNumber}`, { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 });
  } catch (err) {
    console.error(`Failed to fetch PR diff: ${err.message}`);
    process.exit(1);
  }

  if (!diff.trim()) {
    console.log('PR has no diff. Nothing to review.');
    process.exit(0);
  }

  // Truncate very large diffs to avoid token limits
  const MAX_DIFF_CHARS = 60000;
  const truncated = diff.length > MAX_DIFF_CHARS;
  const diffToReview = truncated ? diff.slice(0, MAX_DIFF_CHARS) + '\n\n... [diff truncated]' : diff;

  console.log(`Diff size: ${diff.length} chars${truncated ? ' (truncated for review)' : ''}. Sending to AI...`);

  const messages = [
    { role: 'user', content: `Review this pull request diff:\n\n\`\`\`diff\n${diffToReview}\n\`\`\`` }
  ];

  const result = await callLLM(REVIEW_PROMPT, messages, [], { complex: true });
  const review = result.text;

  if (!review || !review.trim()) {
    console.error('AI returned empty review.');
    process.exit(1);
  }

  console.log('\n--- AI Review ---\n');
  console.log(review);
  console.log('\n--- End Review ---\n');

  // Post as PR comment
  const commentBody = `## 🤖 AI Code Review (PR #${prNumber})\n\n${review}\n\n---\n_Generated by Wingman AI PR Review_`;

  try {
    execSync(`gh pr comment ${prNumber} --body ${JSON.stringify(commentBody)}`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    console.log(`Review posted as comment on PR #${prNumber}.`);
  } catch (err) {
    console.error(`Failed to post comment: ${err.message}`);
    console.log('Review output above can be manually posted.');
    process.exit(1);
  }
}

main().catch(err => {
  console.error('Fatal error:', err.message);
  process.exit(1);
});
